apiVersion: v1
kind: Service
metadata:
  app: phonebook-app-pod
  labels:
    app: phonebook-app-pod
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: phonebook-app-pod